CREATE TABLE `suite_result` (
  `SUITE_RESULT_ID` TEXT NOT NULL,
  `SUITE_NAME` TEXT DEFAULT NULL,
  `PROJECT_NAME` TEXT DEFAULT NULL,
  `JOB_NAME` TEXT DEFAULT NULL,
  `JOB_BUILD_NUMBER` INTEGER DEFAULT NULL,
  `JOB_BUILD_URL` TEXT DEFAULT NULL,
  `EXECUTION_RESULT` TEXT DEFAULT NULL,
  `START_TIME` INTEGER DEFAULT NULL,
  `STOP_TIME` INTEGER DEFAULT NULL,
  `NUMBER_OF_CASES` INTEGER DEFAULT NULL,
  `NUMBER_OF_FAILURE` INTEGER DEFAULT NULL,
  `INVISIBLE_ENTRY` INTEGER DEFAULT '0',
  `PRODUCT_UNDER_TASK` TEXT DEFAULT NULL,
  PRIMARY KEY (`SUITE_RESULT_ID`)
)


CREATE TABLE `suite_property` (
  `SUITE_PROPERTY_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `SUITE_RESULT_ID` TEXT NOT NULL,
  `PROPERTY_NAME` TEXT DEFAULT NULL,
  `PROPERTY_VALUE` TEXT DEFAULT NULL,
  PRIMARY KEY (`SUITE_PROPERTY_ID`)
)


CREATE TABLE `task_case` (
  `TASK_CASE_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `SUITE_CLASS` TEXT NOT NULL,
  `CASE_CLASS` TEXT NOT NULL,
  `CASE_METHOD` TEXT NOT NULL,
  `CASE_DATA_INFO` TEXT NOT NULL,
  `CASE_DATA` TEXT DEFAULT '',
  `CASE_ISSUES` TEXT DEFAULT '',
  PRIMARY KEY (`TASK_CASE_ID`)
)


CREATE TABLE `case_result` (
  `CASE_RESULT_ID` TEXT NOT NULL,
  `SUITE_RESULT` TEXT DEFAULT NULL,
  `TASK_CASE_ID` INTEGER DEFAULT '0',
  `EXECUTION_RESULT` TEXT DEFAULT NULL,
  `AUT` TEXT DEFAULT NULL,
  `START_TIME` INTEGER DEFAULT NULL,
  `STOP_TIME` INTEGER DEFAULT NULL,
  `RETRY` INTEGER DEFAULT NULL,
  `CASE_STATION` TEXT DEFAULT NULL,
  `LOG_DIR` TEXT DEFAULT NULL,
  `EXTERNAL_ID` TEXT DEFAULT NULL,
  `CASE_ENV` TEXT DEFAULT NULL,
  PRIMARY KEY (`CASE_RESULT_ID`),
  CONSTRAINT `fk_suite_result` FOREIGN KEY (`SUITE_RESULT`) REFERENCES `suite_result` (`SUITE_RESULT_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_task_case` FOREIGN KEY (`TASK_CASE_ID`) REFERENCES `task_case` (`TASK_CASE_ID`) ON UPDATE CASCADE
)


CREATE TABLE `case_result_metric` (
  `CASE_RESULT_METRIC_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `CASE_RESULT_ID` TEXT DEFAULT NULL,
  `METRIC_GROUP` TEXT DEFAULT NULL,
  `METRIC_NAME` TEXT DEFAULT NULL,
  `METRIC_VALUE` TEXT DEFAULT NULL,
  PRIMARY KEY (`CASE_RESULT_METRIC_ID`),
  CONSTRAINT `fk_case_result` FOREIGN KEY (`CASE_RESULT_ID`) REFERENCES `case_result` (`CASE_RESULT_ID`) ON DELETE CASCADE ON UPDATE CASCADE
)
