# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"


  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.gui = false
  end


  config.vm.network "forwarded_port", guest: 3306, host: 13306
  config.vm.network "forwarded_port", guest: 8080, host: 18080
  config.vm.network "forwarded_port", guest: 8088, host: 18088


  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "~/reactor", "/home/vagrant/reactor"


  config.vm.provision "shell", inline: <<-SHELL
    wget "https://raw.githubusercontent.com/tascape/reactor/master/doc/ubuntu" -O ubuntu
    bash ubuntu
  SHELL

end
